training:
- wsa:
    path: ./data/annotations_polygon/A_P000006_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000006_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000033_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000033_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000001_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000001_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000007_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000007_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000005_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000005_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000016_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000016_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000005_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000005_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000039_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000039_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000014_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000014_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000012_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000012_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000037_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000037_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000018_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000018_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000024_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000024_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000032_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000032_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000026_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000026_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000021_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000021_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000029_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000029_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000004_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000004_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000020_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000020_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000023_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000023_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000016_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000016_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000016_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000016_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000030_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000030_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000013_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000013_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000032_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000032_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000037_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000037_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000017_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000017_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000040_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000040_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000038_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000038_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000010_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000010_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000033_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000033_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000003_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000003_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000034_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000034_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000029_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000029_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000035_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000035_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000014_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000014_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000024_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000024_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000017_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000017_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000004_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000004_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000038_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000038_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000009_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000009_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000020_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000020_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000025_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000025_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000022_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000022_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000027_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000027_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000017_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000017_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000010_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000010_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000014_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000014_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000004_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000004_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000030_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000030_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000036_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000036_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000011_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000011_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000035_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000035_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000005_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000005_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000018_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000018_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000007_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000007_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000003_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000003_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000031_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000031_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000015_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000015_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000019_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000019_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000015_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000015_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000013_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000013_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000011_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000011_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000028_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000028_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000036_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000036_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000012_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000012_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000034_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000034_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000019_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000019_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000006_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000006_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000011_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000011_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000007_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000007_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000009_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000009_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000031_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000031_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000002_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000002_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/A_P000003_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/A_P000003_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000001_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000001_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/D_P000002_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/D_P000002_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000001_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000001_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/B_P000002_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/B_P000002_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000021_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000021_PAS_CPG.tif
- wsa:
    path: ./data/annotations_polygon/C_P000022_polygon.xml
  wsi:
    path: ./data/images/pas-cpg/C_P000022_PAS_CPG.tif